import * as React from 'react';
import type { IFancyListProps } from './IFancyListProps';
import { IListItem } from './IListItem';
interface IFancyListState {
    items: IListItem[];
    categories: string[];
    selectedCategory: string;
    expandedItems: Set<number>;
    expandedCategories: Set<string>;
    loading: boolean;
    error: string;
    titleImageError: boolean;
    titleImageValidationError: string | null;
    titleImageLoadError: boolean;
    filterImageValidationError: string | null;
    filterImageLoadError: boolean;
}
export default class FancyList extends React.Component<IFancyListProps, IFancyListState> {
    private userHasManuallySelected;
    constructor(props: IFancyListProps);
    componentDidMount(): void;
    componentDidUpdate(prevProps: IFancyListProps): void;
    private loadListData;
    private detectDescriptionType;
    private isImageUrl;
    private isRichText;
    private handleCategoryClick;
    private handleItemToggle;
    private handleCategoryToggle;
    private getFilteredItems;
    private getBackgroundStyle;
    private getShapeRadius;
    private getGradientStyle;
    private getFilterBorderRadius;
    private getTextDecoration;
    private getCategorySectionFontStyle;
    private getSubjectSectionFontStyle;
    private getDescriptionSectionFontStyle;
    private getCategorySectionBackgroundStyle;
    private getSubjectSectionBackgroundStyle;
    private getDescriptionSectionBackgroundStyle;
    private groupItemsByCategory;
    private groupItemsBySubject;
    private getFilterBackgroundStyle;
    private applyCategoryAutoExpand;
    private applySubjectAutoExpand;
    private checkFilterImage;
    private hexToRgba;
    private validateImageFileType;
    private checkTitleImage;
    private getTitleStyle;
    private renderTitle;
    private renderDescriptionContent;
    private renderTextDescription;
    private renderImageDescription;
    private renderRichTextDescription;
    private renderAttachments;
    render(): React.ReactElement<IFancyListProps>;
}
export {};
//# sourceMappingURL=FancyList.d.ts.map